wandb_version: 1

episodic_memory.adc_weighting:
  value: true
episodic_memory.capacity:
  value: 512
episodic_memory.fill_parallel_to_buffer:
  value: false
episodic_memory.prune_fraction:
  value: 0.392867580694561
episodic_memory.replace_by_acd:
  value: true
episodic_memory.std_multiplier:
  value: 0.7569282696090432
episodic_memory.use_acd:
  value: false
