wandb_version: 1

episodic_memory.adc_weighting:
  value: true
episodic_memory.capacity:
  value: 2048
episodic_memory.fill_parallel_to_buffer:
  value: false
episodic_memory.prune_fraction:
  value: 0.6990438096470704
episodic_memory.replace_by_acd:
  value: true
episodic_memory.std_multiplier:
  value: 0.9323290440213324
episodic_memory.use_acd:
  value: false
