wandb_version: 1

episodic_memory.adc_weighting:
  value: false
episodic_memory.capacity:
  value: 2048
episodic_memory.fill_parallel_to_buffer:
  value: true
episodic_memory.prune_fraction:
  value: 0.2942755783867438
episodic_memory.replace_by_acd:
  value: false
episodic_memory.std_multiplier:
  value: 0.7919652638031055
episodic_memory.use_acd:
  value: true
