wandb_version: 1

episodic_memory.adc_weighting:
  value: false
episodic_memory.capacity:
  value: 512
episodic_memory.fill_parallel_to_buffer:
  value: false
episodic_memory.prune_fraction:
  value: 0.5475208299013067
episodic_memory.replace_by_acd:
  value: true
episodic_memory.std_multiplier:
  value: 0.8897283505727023
episodic_memory.use_acd:
  value: true
