wandb_version: 1

episodic_memory.adc_weighting:
  value: true
episodic_memory.capacity:
  value: 256
episodic_memory.fill_parallel_to_buffer:
  value: false
episodic_memory.prune_fraction:
  value: 0.572169004514033
episodic_memory.replace_by_acd:
  value: false
episodic_memory.std_multiplier:
  value: 0.7321304308036038
episodic_memory.use_acd:
  value: false
