wandb_version: 1

episodic_memory.adc_weighting:
  value: true
episodic_memory.capacity:
  value: 512
episodic_memory.fill_parallel_to_buffer:
  value: true
episodic_memory.prune_fraction:
  value: 0.15308086363624465
episodic_memory.replace_by_acd:
  value: true
episodic_memory.std_multiplier:
  value: 0.6287411105234794
episodic_memory.use_acd:
  value: true
